enable: etcd
etcd:
  rootDirectory: opensocket
  address: [ 10.10.9.100:31398 ]
  username: ''
  password: ''

zookeeper:
  schema: opensocket
  address: [ localhost:12181 ]
  username: ''
  password: ''

